### ISSUE TITLE
Add a svgbob binary

### ISSUE THREAD

**Issue by jonhoo** [ivanceras/svgbobrus#3]
The crate currently doesn't hold a binary that reads a diagram specification and produces an SVG. This would be a great addition, and would allow users to use svgbobrus by simply running `cargo install svgbob`.

**Comment by ivanceras** [comment]
I haven't done a crate that are used in command line, though a pull request is always welcomed.

**Comment by jonhoo** [comment]
Working on one as we speak :)

**Comment by ivanceras** [comment]
Cool!. I'm working on the optimizer too, it's harder than I thought :(
